Carcel\Bundle\UserBundle\Entity\User:
    type:  entity
    table: carcel_user_user
    repositoryClass: Carcel\Bundle\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
